### ISSUE TITLE
Could you add a nano favicon?  ;)

### ISSUE THREAD

**Issue by TimTerwijn** [JulianSchmidtke/NanoBacklog#2]

**Comment by TimTerwijn** [comment]
Or broccoli

**Comment by JulianSchmidtke** [comment]
Do you have one i am allowed to use under MIT license?

**Comment by JulianSchmidtke** [comment]
Added a favicon i like in  00add6b7eaae294a14e43dac6128d37ce9182c59

**Comment by TimTerwijn** [comment]
nope, but this one looks good enough :)
